### ISSUE TITLE
Error: invalid initialization of non-const reference

### ISSUE THREAD

**Issue by Aykelith** [eXpl0it3r/SmallGameEngine#3]
I'm receiving this error:

     State.cpp:6:24: error: invalid initialization of non-const reference of type ‘StateMachine&’ from an rvalue of type ‘<brace-enclosed initializer list>’
      , m_replacing{ replace }

**Comment by eXpl0it3r** [comment]
Are you building with a C++11 compiler and have C++11 active?

**Comment by Aykelith** [comment]
Yes, actually I downloaded the repository.

**Comment by eXpl0it3r** [comment]
What is your build command and compiler?
It builds without errors on my end with MinGW-w64 GCC 5.1.0 and `-std=c++11 -Wall -Wextra -pedantic`

**Comment by Aykelith** [comment]
I had GCC 4.8.4 but now I upgraded to 5.1 and it's working. Thanks.

**Comment by eXpl0it3r** [comment]
Hmmm odd, because GCC 4.8.1 is listed as C++11 feature complete. Then again if you were using the official MinGW distribution, I wouldn't be surprised if they had something deactivated for whatever strange reason.

Thanks for the report anyways and let me know if there's anything you need help with. :wink:
